import os
import sys
import pytest
import json
import xml.etree.ElementTree as ET
from datetime import datetime

# Add the root directory to the PYTHONPATH
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.utils.helpers import save_dual_persistence

def parse_pytest_xml(xml_path):
    """
    Parses a JUnit XML file generated by pytest to extract functional test results.
    """
    if not os.path.exists(xml_path):
        return {"status": "ERROR", "message": "No XML report found."}
    
    tree = ET.parse(xml_path)
    root = tree.getroot()
    
    testsuite = root.find("testsuite")
    if testsuite is None:
        return {"status": "ERROR", "message": "Invalid XML structure."}
    
    total_tests = int(testsuite.get("tests", 0))
    failures = int(testsuite.get("failures", 0))
    errors = int(testsuite.get("errors", 0))
    skipped = int(testsuite.get("skipped", 0))
    time = testsuite.get("time", "0.0")
    
    passed = total_tests - failures - errors - skipped
    
    details = []
    for testcase in testsuite.findall("testcase"):
        name = testcase.get("name")
        classname = testcase.get("classname")
        status = "PASSED"
        error_msg = None
        
        failure = testcase.find("failure")
        error = testcase.find("error")
        if failure is not None:
            status = "FAILED"
            error_msg = failure.text
        elif error is not None:
            status = "ERROR"
            error_msg = error.text
        
        details.append({
            "test_name": name,
            "suite": classname,
            "status": status,
            "error_message": error_msg
        })
    
    return {
        "summary": {
            "total": total_tests,
            "passed": passed,
            "failed": failures,
            "errors": errors,
            "skipped": skipped,
            "duration_sec": float(time)
        },
        "details": details
    }

def main():
    print("====================================================")
    print("🚀 EJECUTANDO PRUEBAS FUNCIONALES - Fase 01")
    print("====================================================")
    
    # Define paths
    reports_dir = "tests/reports/functional"
    temp_xml = "tests/temp_functional_report.xml"
    os.makedirs(os.path.dirname(temp_xml), exist_ok=True)
    
    # Run pytest
    pytest_args = [
        "tests/functional/",
        f"--junitxml={temp_xml}",
        "-v"
    ]
    
    exit_code = pytest.main(pytest_args)
    
    # Parse results
    results = parse_pytest_xml(temp_xml)
    
    # Build final report
    final_report = {
        "phase": "02_loader_preprocessor",
        "test_type": "functional",
        "timestamp": datetime.now().isoformat(),
        "overall_status": "SUCCESS" if exit_code == 0 else "FAILURE",
        "results": results,
        "environment": {
            "python_version": sys.version,
            "platform": sys.platform
        }
    }
    
    # Apply Dual Persistence
    save_dual_persistence(
        data=final_report,
        base_path=reports_dir,
        filename="phase_02_functional_tests"
    )
    
    # Cleanup temp XML
    if os.path.exists(temp_xml):
        os.remove(temp_xml)
    
    print(f"\n✅ Reporte de Pruebas Funcionales generado en: {reports_dir}")
    print(f"📊 Resumen: {results['summary']['passed']}/{results['summary']['total']} PASSED")
    
    # Exit with correct code
    sys.exit(exit_code)

if __name__ == "__main__":
    main()
